"""Pure, model-free primitives for structured-rubric evolution."""

from .feedback import criterion_fitness, extract_rubric_feedback
from .patch import apply_rubric_patch, diff_rubrics, plan_artifact_refresh
from .specialize import (
    SpecializeParseError,
    assemble_specialized_pairwise_prediction,
    build_specialize_candidate,
    detect_specialize_trigger,
    deterministic_child_node_id,
    evaluate_specialize_candidate,
    execute_offline_m1,
    parse_child_proposal_response,
    parse_cluster_proposal_response,
    parse_error_signature_response,
    project_pairwise_prediction,
)
from .specialize_types import (
    ChildCriterionProposal,
    ChildDiagnostic,
    ClusterProposal,
    ErrorSignature,
    ErrorSignatureOutput,
    SemanticCluster,
    SpecializeCandidate,
    SpecializeEvaluation,
    SpecializeManagerRequestSpec,
    SpecializeTriggerDecision,
    SubtreeDiagnostic,
)
from .specialize_manager import SpecializeManager, SpecializeManagerFailure
from .types import (
    ArtifactRefreshPlan,
    CandidateAcceptancePolicy,
    CandidateEvaluation,
    EditCandidate,
    ErrorSampleRef,
    EvolutionContext,
    EvolutionDecision,
    NodeFeedback,
    OperatorKind,
    RubricDiff,
    RubricFeedback,
    RubricPatch,
    evaluate_candidate,
)

__all__ = [
    "ArtifactRefreshPlan",
    "CandidateAcceptancePolicy",
    "CandidateEvaluation",
    "ChildCriterionProposal",
    "ChildDiagnostic",
    "ClusterProposal",
    "EditCandidate",
    "ErrorSampleRef",
    "ErrorSignature",
    "ErrorSignatureOutput",
    "EvolutionContext",
    "EvolutionDecision",
    "NodeFeedback",
    "OperatorKind",
    "RubricDiff",
    "RubricFeedback",
    "RubricPatch",
    "SemanticCluster",
    "SpecializeCandidate",
    "SpecializeEvaluation",
    "SpecializeManagerRequestSpec",
    "SpecializeManager",
    "SpecializeManagerFailure",
    "SpecializeParseError",
    "SpecializeTriggerDecision",
    "SubtreeDiagnostic",
    "apply_rubric_patch",
    "assemble_specialized_pairwise_prediction",
    "build_specialize_candidate",
    "criterion_fitness",
    "diff_rubrics",
    "detect_specialize_trigger",
    "deterministic_child_node_id",
    "evaluate_candidate",
    "evaluate_specialize_candidate",
    "execute_offline_m1",
    "extract_rubric_feedback",
    "plan_artifact_refresh",
    "parse_child_proposal_response",
    "parse_cluster_proposal_response",
    "parse_error_signature_response",
    "project_pairwise_prediction",
]
